src/MijnsubclubBundle/Entity/Rdwresponse.php
<?php

namespace MijnsubclubBundle\Entity;

use Symfony\Component\Serializer\Annotation;
use DateTime;


class Rdwresponse
{
    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $aantal_cilinders;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $aantal_deuren;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $aantal_wielen;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $aantal_zitplaatsen;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $afstand_hart_koppeling_tot_achterzijde_voertuig;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $afstand_voorzijde_voertuig_tot_hart_koppeling;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $api_gekentekende_voertuigen_assen;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $api_gekentekende_voertuigen_brandstof;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $api_gekentekende_voertuigen_carrosserie;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $api_gekentekende_voertuigen_carrosserie_specifiek;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $api_gekentekende_voertuigen_voertuigklasse;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $breedte;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $bruto_bpm;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $cilinderinhoud;

    /**
     * @var string
     * @Annotation\Type("DateTime")
     */
    private $datum_eerste_afgifte_nederland;

    /**
     * @var string
     * @Annotation\Type("DateTime")
     */
    private $datum_eerste_toelating;

    /**
     * @var string
     * @Annotation\Type("DateTime")
     */
    private $datum_tenaamstelling;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $eerste_kleur;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $europese_voertuigcategorie;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $export_indicator;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $handelsbenaming;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $inrichting;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $kenteken;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $lengte;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $massa_ledig_voertuig;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $massa_rijklaar;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $maximum_massa_trekken_ongeremd;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $maximum_trekken_massa_geremd;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $merk;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $openstaande_terugroepactie_indicator;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $plaats_chassisnummer;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $technische_max_massa_voertuig;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $toegestane_maximum_massa_voertuig;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $tweede_kleur;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $typegoedkeuringsnummer;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $uitvoering;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $variant;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $vermogen_massarijklaar;

    /**
     * @var string
     * @Annotation\Type("DateTime")
     */
    private $vervaldatum_apk;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $voertuigsoort;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $volgnummer_wijziging_eu_typegoedkeuring;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $wacht_op_keuren;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $wam_verzekerd;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $wielbasis;

    /**
     * @var string
     * @Annotation\Type("string")
     */
    private $zuinigheidslabel;

    /**
     * @return string
     */
    public function getAantalCilinders()
    {
        return $this->aantal_cilinders;
    }

    /**
     * @param string $aantal_cilinders
     */
    public function setAantalCilinders($aantal_cilinders)
    {
        $this->aantal_cilinders = $aantal_cilinders;
    }

    /**
     * @return string
     */
    public function getAantalDeuren()
    {
        return $this->aantal_deuren;
    }

    /**
     * @param string $aantal_deuren
     */
    public function setAantalDeuren($aantal_deuren)
    {
        $this->aantal_deuren = $aantal_deuren;
    }

    /**
     * @return string
     */
    public function getAantalWielen()
    {
        return $this->aantal_wielen;
    }

    /**
     * @param string $aantal_wielen
     */
    public function setAantalWielen($aantal_wielen)
    {
        $this->aantal_wielen = $aantal_wielen;
    }

    /**
     * @return string
     */
    public function getAantalZitplaatsen()
    {
        return $this->aantal_zitplaatsen;
    }

    /**
     * @param string $aantal_zitplaatsen
     */
    public function setAantalZitplaatsen($aantal_zitplaatsen)
    {
        $this->aantal_zitplaatsen = $aantal_zitplaatsen;
    }

    /**
     * @return string
     */
    public function getAfstandHartKoppelingTotAchterzijdeVoertuig()
    {
        return $this->afstand_hart_koppeling_tot_achterzijde_voertuig;
    }

    /**
     * @param string $afstand_hart_koppeling_tot_achterzijde_voertuig
     */
    public function setAfstandHartKoppelingTotAchterzijdeVoertuig($afstand_hart_koppeling_tot_achterzijde_voertuig)
    {
        $this->afstand_hart_koppeling_tot_achterzijde_voertuig = $afstand_hart_koppeling_tot_achterzijde_voertuig;
    }

    /**
     * @return string
     */
    public function getAfstandVoorzijdeVoertuigTotHartKoppeling()
    {
        return $this->afstand_voorzijde_voertuig_tot_hart_koppeling;
    }

    /**
     * @param string $afstand_voorzijde_voertuig_tot_hart_koppeling
     */
    public function setAfstandVoorzijdeVoertuigTotHartKoppeling($afstand_voorzijde_voertuig_tot_hart_koppeling)
    {
        $this->afstand_voorzijde_voertuig_tot_hart_koppeling = $afstand_voorzijde_voertuig_tot_hart_koppeling;
    }

    /**
     * @return string
     */
    public function getApiGekentekendeVoertuigenAssen()
    {
        return $this->api_gekentekende_voertuigen_assen;
    }

    /**
     * @param string $api_gekentekende_voertuigen_assen
     */
    public function setApiGekentekendeVoertuigenAssen($api_gekentekende_voertuigen_assen)
    {
        $this->api_gekentekende_voertuigen_assen = $api_gekentekende_voertuigen_assen;
    }

    /**
     * @return string
     */
    public function getApiGekentekendeVoertuigenBrandstof()
    {
        return $this->api_gekentekende_voertuigen_brandstof;
    }

    /**
     * @param string $api_gekentekende_voertuigen_brandstof
     */
    public function setApiGekentekendeVoertuigenBrandstof($api_gekentekende_voertuigen_brandstof)
    {
        $this->api_gekentekende_voertuigen_brandstof = $api_gekentekende_voertuigen_brandstof;
    }

    /**
     * @return string
     */
    public function getApiGekentekendeVoertuigenCarrosserie()
    {
        return $this->api_gekentekende_voertuigen_carrosserie;
    }

    /**
     * @param string $api_gekentekende_voertuigen_carrosserie
     */
    public function setApiGekentekendeVoertuigenCarrosserie($api_gekentekende_voertuigen_carrosserie)
    {
        $this->api_gekentekende_voertuigen_carrosserie = $api_gekentekende_voertuigen_carrosserie;
    }

    /**
     * @return string
     */
    public function getApiGekentekendeVoertuigenCarrosserieSpecifiek()
    {
        return $this->api_gekentekende_voertuigen_carrosserie_specifiek;
    }

    /**
     * @param string $api_gekentekende_voertuigen_carrosserie_specifiek
     */
    public function setApiGekentekendeVoertuigenCarrosserieSpecifiek($api_gekentekende_voertuigen_carrosserie_specifiek)
    {
        $this->api_gekentekende_voertuigen_carrosserie_specifiek = $api_gekentekende_voertuigen_carrosserie_specifiek;
    }

    /**
     * @return string
     */
    public function getApiGekentekendeVoertuigenVoertuigklasse()
    {
        return $this->api_gekentekende_voertuigen_voertuigklasse;
    }

    /**
     * @param string $api_gekentekende_voertuigen_voertuigklasse
     */
    public function setApiGekentekendeVoertuigenVoertuigklasse($api_gekentekende_voertuigen_voertuigklasse)
    {
        $this->api_gekentekende_voertuigen_voertuigklasse = $api_gekentekende_voertuigen_voertuigklasse;
    }

    /**
     * @return string
     */
    public function getBreedte()
    {
        return $this->breedte;
    }

    /**
     * @param string $breedte
     */
    public function setBreedte($breedte)
    {
        $this->breedte = $breedte;
    }

    /**
     * @return string
     */
    public function getBrutoBpm()
    {
        return $this->bruto_bpm;
    }

    /**
     * @param string $bruto_bpm
     */
    public function setBrutoBpm($bruto_bpm)
    {

src/MijnsubclubBundle/Controller/VoertuigController.php
<?php

namespace MijnsubclubBundle\Controller;

use MijnsubclubBundle\Entity\Rdwresponse;
use MijnsubclubBundle\Entity\Voertuig;
use MijnsubclubBundle\Form\Type\VoertuigType;
use MijnsubclubBundle\MijnsubclubBundle;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\JsonEncoder;

class VoertuigController extends Controller
{
    /**
     * @Route("/voertuigen", name="voertuigen_lijst")
     */
    public function indexAction()
    {
        $repository = $this->getDoctrine()->getRepository('MijnsubclubBundle:Voertuig');
        $subarus = $repository->findBy(array('merk' => 'subaru'));

        return $this->render('MijnsubclubBundle:Voertuig:index.html.twig', array(
            'voertuigen' => $subarus
        ));
    }

    /**
     * @Route("/voertuig/toevoegen", name="voertuig_nieuw")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        $voertuig = new Voertuig();
        $voertuig->setUser($this->getUser());

        $form = $this->createForm(VoertuigType::class, $voertuig)
            ->add('Opslaan', SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($voertuig);
            $entityManager->flush();

            $this->addFlash('success', 'Voertuig succesvol toegevoegd!');

            return $this->redirectToRoute('fos_user_profile_show');
        }

        return $this->render('MijnsubclubBundle:Voertuig:new.html.twig', [
            'voertuig' => $voertuig,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/voertuig/{id}/wijzigen", requirements={"id": "\d+"}, name="voertuig_wijzigen")
     * @param Voertuig $voertuig
     * @param Request  $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Voertuig $voertuig, Request $request)
    {
        if ($this->getUser() !== $voertuig->getUser() && !$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            return $this->denyAccessUnlessGranted('ROLE_EDIT', $voertuig, 'You cannot edit this item.');
        }

        $entityManager = $this->getDoctrine()->getManager();
        $form = $this->createForm(VoertuigType::class, $voertuig);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->flush();
            return $this->redirectToRoute('fos_user_profile_show');
        }
        return $this->render('MijnsubclubBundle:Voertuig:edit.html.twig', [
            'voertuig' => $voertuig,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/voertuig/{id}", name="voertuig_detail")
     * @param Voertuig $voertuig
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function detailAction(Voertuig $voertuig)
    {
        if ($this->getUser() !== $voertuig->getUser() && !$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            return $this->denyAccessUnlessGranted('ROLE_EDIT', $voertuig, 'You cannot edit this item.');
        }

        $kenteken = strtoupper($voertuig->getKenteken());
        $kenteken = str_replace('-', '', $kenteken);

        /** @var \GuzzleHttp\Client $client */
        $client   = $this->get('guzzle.client.api_rdw');
        $response = $client->get('?kenteken=' . $kenteken);

        $content = (string)$response->getBody();

        $serializer = $this->get('serializer');

        $result = $serializer->deserialize($content, 'MijnsubclubBundle\Entity\Rdwresponse[]', 'json');

        return $this->render('MijnsubclubBundle:Voertuig:detail.html.twig', array(
            'voertuig' => $voertuig,
            'rdw_response' => $result
        ));
    }

    /**
     * @Route("/rdw.{_format}",
     *     defaults={"_format": "html"},
     *     options = { "expose" = true },
     *     requirements={
     *         "_format": "html|json",
     *     },
     *     name="rdw_call"
     * )
     * @param Request $request
     * @param         $_format
     * @return Response
     */
    public function rdwcallAction(Request $request, $_format)
    {
        /** @var \GuzzleHttp\Client $client */
        $client   = $this->get('guzzle.client.api_rdw');

        if ($kenteken = $request->query->get('kenteken')) {
            $kenteken = strtoupper($kenteken);
            $kenteken = str_replace('-', '', $kenteken);

            $response = $client->get('?kenteken=' . $kenteken);
        } else {
            $response = $client->get('');
        }

        $content = (string)$response->getBody();

        $serializer = $this->get('jms_serializer');

        if ($_format == 'json'){
            return new Response($content);
        } else {
            return new Response($serializer->deserialize($content, 'MijnsubclubBundle\Entity\Rdwresponse[]', $_format));
        }

    }

}

src/MijnsubclubBundle/Resources/views/Voertuig/detail.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="page-header">
        <h1>
            <span class="fa fa-car"></span>
            Voertuig {{ voertuig.kenteken }}
            {% for kenteken in rdw_response %}
                <span class="pull-right"><small>Vervaldatum APK: {{ kenteken.vervaldatumApk }}</small></span>
            {% endfor %}
        </h1>
    </div>

    {% for kenteken in rdw_response %}
        <div class="row">
            <div class="col-md-4"><strong>aantal_cilinders:</strong></div>
            <div class="col-md-8">{{ kenteken.aantalCilinders }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>aantal_deuren:</strong></div>
            <div class="col-md-8">{{ kenteken.aantalDeuren }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>aantal_wielen:</strong></div>
            <div class="col-md-8">{{ kenteken.aantalWielen }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>aantal_zitplaatsen:</strong></div>
            <div class="col-md-8">{{ kenteken.aantalZitplaatsen }}</div>
        </div>
        <div class="row">
            <div class="col-md-4"><strong>afstand_hart_koppeling_tot_achterzijde_voertuig:</strong></div>
            <div class="col-md-8">{{ kenteken.afstandHartKoppelingTotAchterzijdeVoertuig }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>afstand_voorzijde_voertuig_tot_hart_koppeling:</strong></div>
            <div class="col-md-8">{{ kenteken.afstandVoorzijdeVoertuigTotHartKoppeling }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>breedte:</strong></div>
            <div class="col-md-8">{{ kenteken.breedte }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>bruto_bpm:</strong></div>
            <div class="col-md-8">{{ kenteken.brutoBpm }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>cilinderinhoud:</strong></div>
            <div class="col-md-8">{{ kenteken.cilinderinhoud }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>datum_eerste_afgifte_nederland:</strong></div>
            <div class="col-md-8">{{ kenteken.datumEersteAfgifteNederland }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>datum_eerste_toelating:</strong></div>
            <div class="col-md-8">{{ kenteken.datumEersteToelating }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>datum_tenaamstelling:</strong></div>
            <div class="col-md-8">{{ kenteken.datumTenaamstelling }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>eerste_kleur:</strong></div>
            <div class="col-md-8">{{ kenteken.eersteKleur }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>europese_voertuigcategorie:</strong></div>
            <div class="col-md-8">{{ kenteken.europeseVoertuigcategorie }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>export_indicator:</strong></div>
            <div class="col-md-8">{{ kenteken.exportIndicator }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>handelsbenaming:</strong></div>
            <div class="col-md-8">{{ kenteken.handelsbenaming }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>inrichting:</strong></div>
            <div class="col-md-8">{{ kenteken.inrichting }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>kenteken:</strong></div>
            <div class="col-md-8">{{ kenteken.kenteken }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>lengte:</strong></div>
            <div class="col-md-8">{{ kenteken.lengte }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>massa_ledig_voertuig:</strong></div>
            <div class="col-md-8">{{ kenteken.massaLedigVoertuig }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>massa_rijklaar:</strong></div>
            <div class="col-md-8">{{ kenteken.massaRijklaar }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>maximum_massa_trekken_ongeremd:</strong></div>
            <div class="col-md-8">{{ kenteken.maximumMassaTrekkenOngeremd }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>maximum_trekken_massa_geremd:</strong></div>
            <div class="col-md-8">{{ kenteken.maximumTrekkenMassaGeremd }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>merk:</strong></div>
            <div class="col-md-8">{{ kenteken.merk }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>openstaande_terugroepactie_indicator:</strong></div>
            <div class="col-md-8">{{ kenteken.openstaandeTerugroepactieIndicator }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>plaats_chassisnummer:</strong></div>
            <div class="col-md-8">{{ kenteken.plaatsChassisnummer }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>technische_max_massa_voertuig:</strong></div>
            <div class="col-md-8">{{ kenteken.technischeMaxMassaVoertuig }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>toegestane_maximum_massa_voertuig:</strong></div>
            <div class="col-md-8">{{ kenteken.toegestaneMaximumMassaVoertuig }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>tweede_kleur:</strong></div>
            <div class="col-md-8">{{ kenteken.tweedeKleur }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>typegoedkeuringsnummer:</strong></div>
            <div class="col-md-8">{{ kenteken.typegoedkeuringsnummer }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>uitvoering:</strong></div>
            <div class="col-md-8">{{ kenteken.uitvoering }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>variant:</strong></div>
            <div class="col-md-8">{{ kenteken.variant }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>vermogen_massarijklaar:</strong></div>
            <div class="col-md-8">{{ kenteken.vermogenMassarijklaar }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>vervaldatum_apk:</strong></div>
            <div class="col-md-8">{{ kenteken.vervaldatumApk }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>voertuigsoort:</strong></div>
            <div class="col-md-8">{{ kenteken.voertuigsoort }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>volgnummer_wijziging_eu_typegoedkeuring:</strong></div>
            <div class="col-md-8">{{ kenteken.volgnummerWijzigingEuTypegoedkeuring }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>wacht_op_keuren:</strong></div>
            <div class="col-md-8">{{ kenteken.wachtOpKeuren }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>wam_verzekerd:</strong></div>
            <div class="col-md-8">{{ kenteken.wamVerzekerd }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>wielbasis:</strong></div>
            <div class="col-md-8">{{ kenteken.wielbasis }}</div>
        </div>

        <div class="row">
            <div class="col-md-4"><strong>zuinigheidslabel:</strong></div>
            <div class="col-md-8">{{ kenteken.zuinigheidslabel }}</div>
        </div>
    {% endfor %}
{% endblock %}

src/MijnsubclubBundle/Resources/views/Voertuig/edit.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="page-header">
        <h1>
            <span class="glyphicon glyphicon-user"></span>
            Voertuig {{ voertuig.merk }} {{ voertuig.model }} - {{ voertuig.kenteken }} aanpassen
        </h1>
    </div>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="form-group">
        <label class="col-sm-2"></label>
        <div class="col-sm-10">
            <input type="submit" class="btn btn-default" value="Opslaan"/>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script>
        $('input#mijnsubclubbundle_voertuig_kenteken').on('keyup',function(){
            var charCount = $(this).val().replace(/\s/g, '').replace(/-/g,"").length;
            var kenteken = $(this).val().replace(/\s/g, '').replace(/-/g,"");

            if (charCount === 6 ){
                var url = Routing.generate('rdw_call', { _format: 'json', kenteken: kenteken});
                $.ajax({
                    method: "GET",
                    url: url
                }).success(function( result ) {
                    $.each(result, function(key,auto) {
                        $('#mijnsubclubbundle_voertuig_merk').val(auto.merk);
                        $('#mijnsubclubbundle_voertuig_model').val(auto.handelsbenaming);
                        $('#mijnsubclubbundle_voertuig_type').val(auto.variant);
                    });


                });
            }

            $(".result").text(charCount + " chars");
        });

    </script>
{% endblock %}

src/MijnsubclubBundle/Resources/views/Voertuig/index.html.twig
{% extends '::base.html.twig' %}

{% block body %}
<div class="page-header">
    <h1>
        <span class="glyphicon glyphicon-user"></span>
        Subaru overzicht
    </h1>
</div>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Model</th>
                    <th>Type</th>
                    <th>Bouwjaar</th>
                    <th><span class="glyphicon glyphicon-edit"></span></th>
                    <th><span class="glyphicon glyphicon-remove"></span></th>
                </tr>
                </thead>
                <tbody>
                {% for subaru in subarus %}
                    <tr>
                        <th scope="row">{{ subaru.id }}</th>
                        <td>{{ subaru.model }}</td>
                        <td>{{ subaru.type }}</td>
                        <td>{{ subaru.bouwjaar }}</td>
                        <td><a href="{{ path("voertuig_aanpassen", { 'id': subaru.id }) }}"><span
                                        class="glyphicon glyphicon-edit"></span></a></td>
                        <td><a href="{{ path("voertuig_verwijder", { 'id': subaru.id }) }}"><span class="glyphicon glyphicon-remove"></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

src/MijnsubclubBundle/Resources/views/Voertuig/new.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="page-header">
        <h1>
            <span class="fa fa-car"></span>
            Nieuw voertuig toevoegen
        </h1>
    </div>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

{% endblock %}


{% block javascripts %}
<script>
    $('input#mijnsubclubbundle_voertuig_kenteken').on('keyup',function(){
        var charCount = $(this).val().replace(/\s/g, '').replace(/-/g,"").length;
        var kenteken = $(this).val().replace(/\s/g, '').replace(/-/g,"");

        if (charCount === 6 ){
            var url = Routing.generate('rdw_call', { _format: 'json', kenteken: kenteken});
            $.ajax({
                method: "GET",
                url: url
            }).success(function( result ) {
                $.each(result, function(key,auto) {
                    $('#mijnsubclubbundle_voertuig_merk').val(auto.merk);
                    $('#mijnsubclubbundle_voertuig_model').val(auto.handelsbenaming);
                    $('#mijnsubclubbundle_voertuig_type').val(auto.variant);
                });


            });
        }

        $(".result").text(charCount + " chars");
    });

</script>
{% endblock %}